'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'

Namespace GamesRadar

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://api.gamesradar.com", IsNullable:=False)> _
    Partial Public Class games

        Private total_rowsField As String

        Private gameField() As gamesGame

        '''<remarks/>
        Public Property total_rows() As String
            Get
                Return Me.total_rowsField
            End Get
            Set(value As String)
                Me.total_rowsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("game")> _
        Public Property game() As gamesGame()
            Get
                Return Me.gameField
            End Get
            Set(value As gamesGame())
                Me.gameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com")> _
    Partial Public Class gamesGame

        Private idField As String

        Private nameField As String

        '''<remarks/>
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://api.gamesradar.com", IsNullable:=False)> _
    Partial Public Class NewDataSet

        Private itemsField2() As GamesRadar.games

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("games")> _
        Public Property Items2() As GamesRadar.games()
            Get
                Return Me.itemsField2
            End Get
            Set(value As games())
                Me.itemsField2 = value
            End Set
        End Property
    End Class


End Namespace