'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'

Namespace GamesRadar


    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://api.gamesradar.com", IsNullable:=False)> _
    Partial Public Class game

        Private idField As String

        Private descriptionField As String

        Private designerField As String

        Private updated_dateField As String

        Private urlField As String

        Private technical_featuresField As String

        Private min_system_specsField As String

        Private recommended_system_specsField As String

        Private multiplayer_modesField As String

        Private nameField() As gameName

        Private platformField() As gamePlatform

        Private genreField() As gameGenre

        Private developersField() As gameDevelopersCompany

        Private publishersField() As gamePublishers

        Private expected_release_dateField() As gameExpected_release_date

        Private release_dateField() As gameRelease_date

        Private upcField() As gameUpc

        Private imagesField() As gameImages

        Private linksField() As gameLinks

        '''<remarks/>
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set(value As String)
                Me.descriptionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property designer() As String
            Get
                Return Me.designerField
            End Get
            Set(value As String)
                Me.designerField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property updated_date() As String
            Get
                Return Me.updated_dateField
            End Get
            Set(value As String)
                Me.updated_dateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set(value As String)
                Me.urlField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property technical_features() As String
            Get
                Return Me.technical_featuresField
            End Get
            Set(value As String)
                Me.technical_featuresField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property min_system_specs() As String
            Get
                Return Me.min_system_specsField
            End Get
            Set(value As String)
                Me.min_system_specsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property recommended_system_specs() As String
            Get
                Return Me.recommended_system_specsField
            End Get
            Set(value As String)
                Me.recommended_system_specsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property multiplayer_modes() As String
            Get
                Return Me.multiplayer_modesField
            End Get
            Set(value As String)
                Me.multiplayer_modesField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("name")> _
        Public Property name() As gameName()
            Get
                Return Me.nameField
            End Get
            Set(value As gameName())
                Me.nameField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("platform")> _
        Public Property platform() As gamePlatform()
            Get
                Return Me.platformField
            End Get
            Set(value As gamePlatform())
                Me.platformField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("genre")> _
        Public Property genre() As gameGenre()
            Get
                Return Me.genreField
            End Get
            Set(value As gameGenre())
                Me.genreField = Value
            End Set
        End Property




        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("expected_release_date")> _
        Public Property expected_release_date() As gameExpected_release_date()
            Get
                Return Me.expected_release_dateField
            End Get
            Set(value As gameExpected_release_date())
                Me.expected_release_dateField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("release_date")> _
        Public Property release_date() As gameRelease_date()
            Get
                Return Me.release_dateField
            End Get
            Set(value As gameRelease_date())
                Me.release_dateField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("upc")> _
        Public Property upc() As gameUpc()
            Get
                Return Me.upcField
            End Get
            Set(value As gameUpc())
                Me.upcField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("images")> _
        Public Property images() As gameImages()
            Get
                Return Me.imagesField
            End Get
            Set(value As gameImages())
                Me.imagesField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("links")> _
        Public Property links() As gameLinks()
            Get
                Return Me.linksField
            End Get
            Set(value As gameLinks())
                Me.linksField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com")> _
    Partial Public Class gameName

        Private usField As String

        Private ukField As String

        '''<remarks/>
        Public Property us() As String
            Get
                Return Me.usField
            End Get
            Set(value As String)
                Me.usField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property uk() As String
            Get
                Return Me.ukField
            End Get
            Set(value As String)
                Me.ukField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com")> _
    Partial Public Class gamePlatform

        Private idField As String

        Private nameField As String

        '''<remarks/>
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com")> _
    Partial Public Class gameGenre

        Private idField As String

        Private nameField As String

        '''<remarks/>
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com")> _
    Partial Public Class gameDevelopersCompany

        Private idField As String

        Private nameField As String

        '''<remarks/>
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com")> _
    Partial Public Class gamePublishers

        Private usField As String

        Private ukField As String

        '''<remarks/>
        Public Property us() As String
            Get
                Return Me.usField
            End Get
            Set(value As String)
                Me.usField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property uk() As String
            Get
                Return Me.ukField
            End Get
            Set(value As String)
                Me.ukField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com")> _
    Partial Public Class gameExpected_release_date

        Private usField As String

        Private ukField As String

        '''<remarks/>
        Public Property us() As String
            Get
                Return Me.usField
            End Get
            Set(value As String)
                Me.usField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property uk() As String
            Get
                Return Me.ukField
            End Get
            Set(value As String)
                Me.ukField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com")> _
    Partial Public Class gameRelease_date

        Private usField As String

        '''<remarks/>
        Public Property us() As String
            Get
                Return Me.usField
            End Get
            Set(value As String)
                Me.usField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com")> _
    Partial Public Class gameUpc

        Private usField As String

        Private ukField As String

        '''<remarks/>
        Public Property us() As String
            Get
                Return Me.usField
            End Get
            Set(value As String)
                Me.usField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property uk() As String
            Get
                Return Me.ukField
            End Get
            Set(value As String)
                Me.ukField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com")> _
    Partial Public Class gameImages

        Private thumbnailField As String

        '''<remarks/>
        Public Property thumbnail() As String
            Get
                Return Me.thumbnailField
            End Get
            Set(value As String)
                Me.thumbnailField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://api.gamesradar.com")> _
    Partial Public Class gameLinks

        Private rssField As String

        '''<remarks/>
        Public Property rss() As String
            Get
                Return Me.rssField
            End Get
            Set(value As String)
                Me.rssField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    
    Partial Public Class NewDataSet

        Private itemsField() As GamesRadar.game

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("game")> _
        Public Property Items() As GamesRadar.game()
            Get
                Return Me.itemsField
            End Get
            Set(value As GamesRadar.game())
                Me.itemsField = value
            End Set
        End Property
    End Class


End Namespace